version: "3.9"

services:
  web:
    build: .
    container_name: dbserver_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/src
    environment:
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000
